export { default as AboutUs } from "./aboutUs/AboutUs";
export { default as Chef } from "./chef/Chef";
export { default as Contact } from "./contact/Contact";
export { default as Gallery } from "./gallery/Gallery";
export { default as Header } from "./header/Header";
export { default as Intro } from "./intro/Intro";
export { default as Laurels } from "./laurels/Laurels";
export { default as Menu } from "./menu/Menu";
export { default as Footer } from "./footer/Footer";
